### PR TITLE
Added experiment_type to Experiment.editable_fields

### PR DESCRIPTION
**Pull request by andriisoldatenko**
## Add ability to edit experiment_type for project experiments.

I found that this feature is working using `curl` and trying to sync python client.

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
Please review @mauerbac @ollamh

**Comment by ollamh** [comment]
+1

**Comment by andriisoldatenko** [comment]
any updates?

**Comment by andriisoldatenko** [comment]
cc @ajrharris @mauerbac

**Comment by amilstead** [comment]
@andriisoldatenko Sorry for the delay -- I'll be taking a look at this and #19 today!

**Comment by amilstead** [comment]
@andriisoldatenko Sorry for the slowness on this one, I need to check with our PMs internally about this particular change. I should have an update shortly!

**Comment by amilstead** [comment]
@andriisoldatenko We're getting some PyPI ownership stuff sorted out internally. As soon as that is taken care of, I'll do a version bump and push this new code.

**Pull request merged**
