### PR TITLE
Added PY3 compliance

### PR DESCRIPTION
**Pull request by ollamh**
# Description 

Currently code doesn't support Python 3

# PR description

Added some tweaks to the code in order to work with Python 3.4 and Python 2.7.
- Using either urlparse  or urllib.parse with try .. except ...
- Using either iteritems or items with try .. except ...

# Tests

No unit tests. Manually tested on Python 3.4 and Python 2.7. So far so good.

### CODE REVIEW

**Comment by mauerbac** [comment]
Thanks @ollamh for addressing issue #17 ! I've just reviewed your PR and it looks good to me. My only concern was around breaking Python 2.7 support, but that doesn't look like an issue.

**Comment by ollamh** [comment]
Thanks @mauerbac! I signed that CLA.

**Comment by mauerbac** [comment]
Great! Thanks for the help @ollamh

**Comment by ollamh** [comment]
No problem @mauerbac !

**Pull request merged**
